FROM ubuntu:20.04

LABEL maintainer='nithin246'

ENV TZ=Asia/Kolkata \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install tzdata

RUN apt-get install wget -y
RUN apt-get install -y git

RUN git clone https://github.com/Nithin-optit/play-1.git

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y maven \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 80

CMD ["apachectl", "-D","FOREGROUND"]
